// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nifprsrrldjhijcfbemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZnByc3JybGRqaGlqY2ZiZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzAyNzAsImV4cCI6MjA2NjU0NjI3MH0.L6hmoq_ttMz0oo_RdRZRYyM7pdxvyDzpebIHJByUJn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);